name: publish-techdocs
run-name: ${{ github.actor }} is building and publishing techdocs
on: [push]
jobs:
  publish-techdocs:
    runs-on: ubuntu-latest

    env:
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'quickstart'
      # In a Software template, Scaffolder will replace {{cookiecutter.component_id | jsonify}}
      # with the correct entity name. This is same as metadata.name in the entity's catalog-info.yaml
      # ENTITY_NAME: '{{ cookiecutter.component_id | jsonify }}'
      TECHDOCS_AZURE_BUCKET_NAME: ${{ secrets.TECHDOCS_AZURE_BUCKET_NAME }}
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Installs Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Installs Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type azureBlobStorage --storage-name $TECHDOCS_AZURE_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME --azureAccountName $AZURE_ACCOUNT_NAME --azureAccountKey $AZURE_ACCOUNT_KEY
      - run: echo "🍏 This job's status is ${{ job.status }}."

# The value for --entity must be the Backstage entity which the generated TechDocs site belongs to. You can find the values in your Entity's catalog-info.yaml file. If namespace is missing in the catalog-info.yaml, use default. The directory structure used in the storage bucket is namespace/kind/name/<files>.